
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build the app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<your-azure-service-connection-name>'
    appName: 'appfortest'
    package: '$(System.DefaultWorkingDirectory)/dist'
  displayName: 'Deploy to Azure Web App'



