# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    echo "Deploying your web app"
    echo "You can add build steps here"
  displayName: 'Build your app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your Azure Service Connection Name>'
    appName: '<Your App Service Name>'
    package: '$(System.DefaultWorkingDirectory)'

